### ISSUE TITLE
用流量时会出现无限上传

### ISSUE THREAD

**Issue by cnjn** [taamarin/ClashforMagisk#22]
用流量刷一会儿抖音就会出现很多上传连接，占用cpu超过50%
![Screenshot_2023-01-30-23-03-18-479_com dashboard kotlin](https://user-images.githubusercontent.com/30923815/215518535-97e9543e-6e4c-449b-a6ae-4af1521d7c5b.jpg)

![Screenshot_2023-01-30-23-17-16-632_com dashboard kotlin](https://user-images.githubusercontent.com/30923815/215518199-474de025-b4a6-4801-94a1-b0ad74c8a23d.jpg)

可以看到src ip和dst ip都是我的本机公网ip。搜了一下，这是本地环回出问题了？参考cfw的issue
 https://github.com/Fndroid/clash_for_windows_pkg/issues/2556

尝试切换meta和premium内核，都有这个问题

**Comment by cnjn** [comment]
内存也不对劲。吃了我将近400兆。日常应该只有10几兆

**Comment by taamarin** [comment]
尝试使用最新的 Kernel-Meta 1.14 或 Alpha
你正在经历同样的事情吗？

**Comment by taamarin** [comment]
https://github.com/taamarin/ClashforMagisk/blob/master/scripts/clash.iptables#L315

**Comment by cnjn** [comment]
> 尝试使用最新的 Kernel-Meta 1.14 或 Alpha 你正在经历同样的事情吗？

我瞄了一眼，我现在用的应该就是最新版的内核。那条commit在我的本机中是存在的
![Screenshot_2023-01-31-00-44-24-996_bin mt plus](https://user-images.githubusercontent.com/30923815/215540351-bf82e7c2-9f8e-406b-9519-115374d48b0a.jpg)

看了看那条commit，看来您是有意修复过了。
但我也观察到我这边是ipv6的无限环回。这个commit对于ipv6是否同样有效呢？
我猜之所以流量才有这个bug，正是因为流量有ipv6地址。
不过在3.0版，ipv6是默认开启的。。。

**Comment by taamarin** [comment]
> > 尝试使用最新的 Kernel-Meta 1.14 或 Alpha 你正在经历同样的事情吗？
> 
> 我瞄了一眼，我现在用的应该就是最新版的内核。那条commit在我的本机中是存在的 ![Screenshot_2023-01-31-00-44-24-996_bin mt plus](https://user-images.githubusercontent.com/30923815/215540351-bf82e7c2-9f8e-406b-9519-115374d48b0a.jpg)
> 
> 看了看那条commit，看来您是有意修复过了。 但我也观察到我这边是ipv6的无限环回。这个commit对于ipv6是否同样有效呢？ 我猜之所以流量才有这个bug，正是因为流量有ipv6地址。 不过在3.0版，ipv6是默认开启的。。。

尝试删除它，或者只是编辑它
或者只是关闭 ipv6 ，如果不使用

**Comment by taamarin** [comment]
你试过TUN，你也体验过Loopback吗？

**Comment by taamarin** [comment]
> 我暂时先把ipv6禁掉

如果你知道如何解决它，请只是 pr。
我很少使用 IPV6，在我的国家 IPV6 分布不均匀

**Comment by cnjn** [comment]
> 
Okay, I'll see if there's another way
Because in China, basically all mobile phones will have an IPv6 address  when using the mobile data🤣

**Comment by cnjn** [comment]
Because you kept replying with Chinese, I thought you were Chinese too. Sorry 😀
