### ISSUE TITLE
3.0版本会一直弹出magisk提示

### ISSUE THREAD

**Issue by kuektic** [taamarin/ClashforMagisk#25]
![Screenshot_20230210-063723.jpg](https://user-images.githubusercontent.com/95989221/217955092-1a861899-6885-4e64-9d7f-d5302855e17e.jpg)

后台运行也会一直弹出提示，只能关闭后台。请问这是bug吗？

**Comment by taamarin** [comment]
> ![Screenshot_20230210-063723.jpg](https://user-images.githubusercontent.com/95989221/217955092-1a861899-6885-4e64-9d7f-d5302855e17e.jpg)
> 
> 后台运行也会一直弹出提示，只能关闭后台。请问这是bug吗？

![Screenshot_20230210-064913](https://user-images.githubusercontent.com/71506581/217964928-cac101ea-2bc8-4703-9027-6382104a6fba.png)

恩，那就对了，
只需关闭 Magisk 中的通知，
或使用此 APK https://t.me/MagiskChangeKing/159
